import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

export default async function MetricasPage() {
  const supabase = createClient();

    const { data: stages } = await supabase
        .from("pipeline_stages")
            .select("id, label, position")
                .order("position", { ascending: true });

                  const { data: leads } = await supabase.from("leads").select("stage_id, is_urgent");

                    const { count: contactsCount } = await supabase
                        .from("contacts")
                            .select("id", { count: "exact", head: true });

                              const { count: conversationsCount } = await supabase
                                  .from("conversations")
                                      .select("id", { count: "exact", head: true });

                                        const since = new Date();
                                          since.setDate(since.getDate() - 7);

                                            const { count: botMessagesWeek } = await supabase
                                                .from("messages")
                                                    .select("id", { count: "exact", head: true })
                                                        .eq("sender", "bot")
                                                            .gte("created_at", since.toISOString());

                                                              const { count: humanHandoffsWeek } = await supabase
                                                                  .from("messages")
                                                                      .select("id", { count: "exact", head: true })
                                                                          .eq("sender", "human")
                                                                              .gte("created_at", since.toISOString());

                                                                                const { data: qa } = await supabase
                                                                                    .from("qa_reviews")
                                                                                        .select("failure, suggestion, reviewed_at")
                                                                                            .order("reviewed_at", { ascending: false })
                                                                                                .limit(8);

                                                                                                  const stageCounts: Record<string, number> = {};
                                                                                                    (leads ?? []).forEach((l) => {
                                                                                                        stageCounts[l.stage_id] = (stageCounts[l.stage_id] ?? 0) + 1;
                                                                                                          });
                                                                                                            const urgentCount = (leads ?? []).filter((l) => l.is_urgent).length;
                                                                                                            
                                                                                                              const stats = [
                                                                                                                  { label: "Contactos totales", value: contactsCount ?? 0 },
                                                                                                                      { label: "Conversaciones", value: conversationsCount ?? 0 },
                                                                                                                          { label: "Mensajes del bot (7d)", value: botMessagesWeek ?? 0 },
                                                                                                                              { label: "Derivado a humano (7d)", value: humanHandoffsWeek ?? 0 },
                                                                                                                                ];
                                                                                                                                
                                                                                                                                  return (
                                                                                                                                      <div className="p-6 space-y-6 overflow-y-auto h-screen">
                                                                                                                                            <header>
                                                                                                                                                    <h1 className="text-lg font-semibold text-slate-900">Métricas</h1>
                                                                                                                                                            <p className="text-sm text-slate-500">Cómo viene funcionando el agente, última semana.</p>
                                                                                                                                                                  </header>
                                                                                                                                                                  
                                                                                                                                                                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                                                                                                                                                                                {stats.map((s) => (
                                                                                                                                                                                          <div key={s.label} className="rounded-xl border border-slate-200 bg-white p-4">
                                                                                                                                                                                                      <div className="text-xs text-slate-400">{s.label}</div>
                                                                                                                                                                                                                  <div className="mt-1 text-2xl font-semibold text-slate-900">{s.value}</div>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                        <h2 className="text-sm font-medium text-slate-700 mb-2">Leads por etapa</h2>
                                                                                                                                                                                                                                                                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                                                                                                                                                                                                                                                                          {(stages ?? []).map((s) => (
                                                                                                                                                                                                                                                                                      <div key={s.id} className="rounded-xl border border-slate-200 bg-white p-4">
                                                                                                                                                                                                                                                                                                    <div className="text-xs text-slate-400">{s.label}</div>
                                                                                                                                                                                                                                                                                                                  <div className="mt-1 text-2xl font-semibold text-slate-900">{stageCounts[s.id] ?? 0}</div>
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-sm font-medium text-slate-700 mb-2">Reclamos urgentes abiertos</h2>
                                                                                                                                                                                                                                                                                                                                                                            <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-2xl font-semibold text-rose-700 w-fit">
                                                                                                                                                                                                                                                                                                                                                                                      {urgentCount}
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-sm font-medium text-slate-700 mb-2">Últimas notas del QA nocturno</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                          {(qa ?? []).length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm text-slate-400">Sin notas todavía.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ul className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {(qa ?? []).map((q, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li key={i} className="rounded-lg border border-slate-200 bg-white p-3 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-slate-700">{q.failure}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {q.suggestion && <div className="text-slate-400 mt-1">{q.suggestion}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
